# Generated by Django 3.0.5 on 2020-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deveui', models.CharField(default='', max_length=70)),
                ('timestamp', models.CharField(default='', max_length=70)),
                ('payload_ciphered', models.CharField(default='', max_length=70)),
                ('payload_deciphered', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
